### ISSUE TITLE
Compile single job or service

### ISSUE THREAD

**Issue by saadjutt01** [sasjs/cli#501] opened 2021-02-20 11:46 UTC
Two more actions 

`sasjs compile` -> does everything in a project, works locally
`sasjs compile job` -> compiles  a single job, can work anywhere
`sasjs compile service` -> compiles a single service, can work anywhere

the output would be saved as per the `--output` location,
- if in a project, then it would go in the root of the `sasjsbuild` folder
- if global, create `sasjsbuild` and place there

**Comment by allanbowe** [comment] 2021-02-20 12:04
closed as duplicate of #469

**Closed** 2021-02-20 12:04 UTC
