### ISSUE TITLE
Deploy compiled SAS code as code instead of job definition

### ISSUE THREAD

**Issue by mblauw-sas** [sasjs/cli#1230] opened 2022-07-21 09:25 UTC
For our current project, we would like to deploy the compiled SAS code as code, instead of job definitions. We were wondering if this would be difficult to add to sasjs.

We want to do this for the following reasons
- The client does not have an external scheduling tool
- We do not have access to the machine itself to setup scheduling, nor to any other machine that will keep running. Also we are not allowed to run x-commands
- The client prefers to use SAS Job Execution. The solution we found most easy (and convenient) to implement would be to have one big script with a lot of %includes. Scheduling can then be done by just triggering this single script. However, this approach is not possible if the deployed contents are job definitions.

**Comment by allanbowe** [comment] 2022-07-21 09:43
Duplicate of #991 

We'd love to build this.  Is there any chance we can get some project engagement or sponsorship to fund the feature?

**Comment by allanbowe** [comment] 2022-07-21 09:57
Just to point out here, it IS possible to run all the jobs using [mv_jobflow](https://core.sasjs.io/mv__jobflow_8sas.html) macro, although it needs some additional work for Viya 4 compatibility.  Again, happy to help with this if access to a Viya 4 instance can be arranged.

**Comment by allanbowe** [comment] 2022-07-21 09:58
another option is to write a macro wrapper using [mv_getjobcode](https://core.sasjs.io/mv__getjobcode_8sas.html) and `%inc` that.

**Comment by mblauw-sas** [comment] 2022-07-21 11:06
Hi Allan, thank you for your comments! I will get back to you on this.

**Comment by allanbowe** [comment] 2022-07-28 22:35
closing this - we can continue discussion in #991

**Closed by allanbowe** 2022-07-28 22:35 UTC
