### ISSUE TITLE
Can't create a context

### ISSUE THREAD

**Issue by PrajwalSD** [sasjs/cli#1010] opened 2021-09-22 17:31 UTC
![image](https://user-images.githubusercontent.com/9878539/134392768-5c6e0da2-101c-4c56-87f8-1f8efed4c2e2.png)

**Comment by allanbowe** [comment] 2021-09-22 17:55
aha - turns out I can transfer an issue.  Please furnish this one with the requisite details!

**Comment by PrajwalSD** [comment] 2021-09-22 20:45
Sorry about the wrong repo, rushed it. 

JSONs:
[T3_and_source_json.zip](https://github.com/sasjs/cli/files/7213657/T3_and_source_json.zip)

For the context, I was trying to play with SASjs for VS code and I got the below error (really hope I didn't miss anything in the config): 
![image](https://user-images.githubusercontent.com/9878539/134418770-5df27469-debe-4404-82fc-848a5f985778.png)

Used [this](https://blogs.sas.com/content/sgf/2019/01/25/authentication-to-sas-viya/) to get the tokens etc. The auth works fine with T3.

I later installed the CLI to see what was I missing and got the above error. Hope this helps, any help is appreciated here.

P.S. The permissions are fine (I guess), checked the rules (launcher/contexts and compute/contexts for the user group).

**Comment by PrajwalSD** [comment] 2021-09-27 10:20
Anything on this, please?

**Comment by allanbowe** [comment] 2021-09-27 10:38
Thanks for the prod.  Some other things to check:

* which version of the CLI are you using ?  `sasjs v`
* does the CLI work for other commands?  try `sasjs folder list /Public`
* Are you able to create the context manually, using the same user id (`viadmin`)?  This account normally needs special authentication
* Can you try changing `"reuseServerProcesses": "true",` to `"reuseServerProcesses": true,` ?

**Comment by allanbowe** [comment] 2022-07-21 21:13
Hi @PrajwalSD - did our suggestions solve your issue?

**Comment by PrajwalSD** [comment] 2022-07-22 10:15
Sorry, Allan, I didn't get around to working on this. I'm not sure if I
pursue this any further at the moment, will keep you posted if I do.

Thank you very much the follow up

**Comment by allanbowe** [comment] 2022-07-22 10:24
Understood - I'll close it for now, as it's not something we were able to reproduce.  Feel free to re-open or create a new issue though if you have further information!

FYI - since this issue was raised, the VS Code extension now also supports SAS 9 EBI (on Stored Processes) and Base SAS (using [SASjs Server](https://server.sasjs.io)), neither of which require contexts.

**Closed** 2022-07-22 10:25 UTC
Labels: sasjs context
